In [84]:
import numpy as np

class ConvolutionNetwork:
    """
    simple convolutional network
    """
    
    def __init__(self, kernalSize = (1,10), kernalShape=(3,3), kernalStep = 1):
        self.__kernalSize = kernalSize
        self.__kernalShape = kernalShape
        self.__kernalStep = kernalStep
        self.__kernals = np.array([np.random.randn(kernalShape[0], kernalShape[1])
                                  for i in range(kernalSize[0])
                                  for j in range(kernalSize[1])])
    
    def __convolute(self, data):
        dm, dn = data.shape
        km, kn = self.__kernalShape
        self.__filterMapShape = (dm - km)/self.__kernalStep+1, (dn - kn)/self.__kernalStep+1
        kernalMaps = np.arrange(self.__kernalShape[1])
        for k in range(self.__kernalShape[1]):
            kernalGroup = self.kernals[:, k]
            for kernal in kernalGroup:
                kernalMap = np.sum([np.array([
                        np.sum(data[i:i+km, j:j+kn]*kernal)
                        for i in range(0, dm-km+1, self.__kernalStep)
                        for j in range(0, dn-kn+1, self.__kernalStep)
                    ]) for kernal in kernalGroup]
        #kernalMaps[k]=kernalMap
        #for kernal in self.__kernals:
        #    self.__filterMaps = np.array(
        #    [np.sum(data[i:i+km, j:j+kn] * kernal) 
        #     for i in range(0, dm-km+1, self.__kernalStep) 
        #     for j in range(0, dn-kn+1, self.__kernalStep)]
        #).reshape(self.__filterMapShape)
        #    print self.__filterMaps
        #self.__filterMaps = np.random.randn(self.__filterMapShape[0], self.__filterMapShape[1])
        
        
        
        #for i in range(0, self.__filterMapShape[0], 1):
        #    for j in range(0, self.__filterMapShape[1], 1):
        #        self.__filterMaps[i][j] = np.sum(data[i:i+km, j:j+kn]*self.__kernal)
        
        #print self.__filterMaps

        
    def fit(self, data):
        self.__convolute(data)
        pass

if __name__ == '__main__':
    data = np.random.rand(4, 4)
    print data
    cnn = ConvolutionNetwork()
    cnn.fit(data)

SyntaxError: invalid syntax (<ipython-input-84-af728aa68a3c>, line 48)

In [19]:
data = np.random.randn(5,5)
print data[0:3,0:3]

[[-0.13952662  0.1570312  -0.71920374]
 [ 1.24095539  0.9646782   0.25817817]
 [-0.09433619  0.02128432 -0.44333165]]
