In [85]:
# -*-coding:utf-8-*-

import numpy as np


class ConvolutionNetwork:
    """
    simple convolutional network
    """

    def __init__(self, kernalSize=(3, 10), kernalShape=(3, 3), kernalStep=1):
        self.__kernalSize = kernalSize
        self.__kernalShape = kernalShape
        self.__kernalStep = kernalStep
        self.__kernals = np.random.randn(kernalSize[0], kernalSize[1], kernalShape[0], kernalShape[1])

    def __convolute(self, data):
        dm, dn = data.shape
        km, kn = self.__kernalShape
        kernalMapShape = (dm - km) / self.__kernalStep + 1, (dn - kn) / self.__kernalStep + 1
        kernalMaps = []
        for k in range(self.__kernalSize[1]):
            kernalGroup = self.__kernals[:, k]
            
            # TODO: change np.sum to convoluteFunction such sum, mean etc.
            kernalMap = sum([np.array([np.sum(data[i:i + km, j:j + kn] * kernal)
                                       for i in range(0, dm - km + 1, self.__kernalStep)
                                       for j in range(0, dn - kn + 1, self.__kernalStep)
                                       ]).reshape(kernalMapShape) for kernal in kernalGroup])
            kernalMaps.append(kernalMap)
        self.__kernalMaps = np.array(kernalMaps)

        print self.__kernalMaps
    def fit(self, data):
        self.__convolute(data)


if __name__ == '__main__':
    data = np.random.rand(4, 4)
    cnn = ConvolutionNetwork()
    cnn.fit(data)

[[[-1.37961161  1.12294704]
  [-0.61865218 -0.56152676]]

 [[-2.41006578 -1.00599324]
  [-0.84435148 -1.41900572]]

 [[ 1.23225084  2.89429355]
  [ 0.61588324  3.73159031]]

 [[-0.4728081   1.92515915]
  [ 1.14210498 -0.16798226]]

 [[-4.85288376 -4.56052888]
  [-4.66957085 -3.97837708]]

 [[ 7.18773415  6.53776466]
  [ 9.02556555  9.43959403]]

 [[-0.39396955  1.58411907]
  [-1.86277637  0.36039542]]

 [[ 7.6626936   5.20113607]
  [ 7.55970443  6.31405174]]

 [[-2.16300645 -3.18748275]
  [-3.04169383 -3.08125731]]

 [[ 2.52839662  0.58815611]
  [ 3.31778046  1.94692029]]]


In [19]:
data = np.random.randn(5,5)
print data[0:3,0:3]

[[-0.13952662  0.1570312  -0.71920374]
 [ 1.24095539  0.9646782   0.25817817]
 [-0.09433619  0.02128432 -0.44333165]]
